### ISSUE TITLE
Call meta for next page

### ISSUE THREAD

**Issue by vikramsra** [eduvo/PHP-API-Library#1]
First of all thanks for the API. Worked like charm. We stuck @ one place that how to proceed multi page out put. How to call all data or page-wise data.

**Comment by avanderbergh** [comment]
The API client helps you iterate over multi-page output using foreach

If you do:
`$students = $client->students->all();
foreach ($students as $student) {
   ...
}`

It will automatically iterate over multiple pages.

**Comment by vikramsra** [comment]
Thanks for the quick response . All worked well
